### PR TITLE
Yuhanli publish button finish

### PR DESCRIPTION
**Pull request by LIYUHAN22**
frontend publish button finish

### :ballot_box_with_check: Definition of Done checklist
- [ ] Meaningful title and valuable description in pull request
- [ ] Code change tested manually if not covered by automated tests
- [ ] Pull request linked to one or more issues/stories
- [ ] Acceptance criteria of the linked stories satisfied
- [ ] Code change comprehended by those who approved it
- [ ] State of target branch maintained or improved after the code change

### CODE REVIEW

**Comment by platisd** [comment]
This pull request looks the same as the other one that's currently open.

**Comment by LIYUHAN22** [comment]
> This pull request looks the same as the other one that's currently open.

The different is that pull request is a little behind than this, but it has update the README file

**Comment by platisd** [comment]
Why do you have two of them?!

**Comment by LIYUHAN22** [comment]
> Why do you have two of them?!

Coz we think is the same that "make 2 pull request to master" and "make a pull request to one branch and then make another pull request to master". The README is different in this two branch

**Comment by LIYUHAN22** [comment]
> Why do you have two of them?!

README in "Yuhanli" branch is new updated from Bora's branch before

**Comment by platisd** [comment]
Why don't you push the Readme to the branch that has the other changes or why don't you have one branch for the Readme and another only with the rest of the changes?

From all the different options, your current way of doing things is the most unconventional. 😅

**Comment by LIYUHAN22** [comment]
> Why don't you push the Readme to the branch that has the other changes or why don't you have one branch for the Readme and another only with the rest of the changes?
> 
> From all the different options, your current way of doing things is the most unconventional. 😅

Coz the change of the README was not by me, it merged from Bora's branch, and it has been merge to an old branch before I update the newest code... so there have some conflicts in this two branch, so I have create a new branch "Yuhanli_publishButton" and push the code to this branch. So we think is more easier to do to make two pull request to master instead of merge into master after "Yuhanli" and "Yuhanli_publishButton" are merged.😅

**Pull request closed without merging**
