### PR TITLE
change the maxDistance to 500

### PR DESCRIPTION
**Pull request by LIYUHAN22**

### CODE REVIEW

**Review by darmacuong — APPROVED** [review]

**Comment by platisd** [comment]
I am a bit concerned on your code reviewing process. :sweat_smile: 
The [docs](https://github.com/ItJustWorksTM/smce-gd/wiki/Vehicle-Capabilities#ultrasonic-distance-sensor) specify what is the maximum distance for the particular sensor, a piece of information that is also available online when looking for the maximum distance of an SR04 sensor.

**Comment by LIYUHAN22** [comment]
> I am a bit concerned on your code reviewing process. 😅 The [docs](https://github.com/ItJustWorksTM/smce-gd/wiki/Vehicle-Capabilities#ultrasonic-distance-sensor) specify what is the maximum distance for the particular sensor, a piece of information that is also available online when looking for the maximum distance of an SR04 sensor.

Sorry I may be asking a stupid question, does "maxDistance" have to be the maximum distance the sensor can reach?

**Comment by LIYUHAN22** [comment]
> I am a bit concerned on your code reviewing process. 😅 The [docs](https://github.com/ItJustWorksTM/smce-gd/wiki/Vehicle-Capabilities#ultrasonic-distance-sensor) specify what is the maximum distance for the particular sensor, a piece of information that is also available online when looking for the maximum distance of an SR04 sensor.

Sorry we made this mistake, we thought is in "mm" not "cm" at first

**Comment by platisd** [comment]
> > I am a bit concerned on your code reviewing process. sweat_smile The [docs](https://github.com/ItJustWorksTM/smce-gd/wiki/Vehicle-Capabilities#ultrasonic-distance-sensor) specify what is the maximum distance for the particular sensor, a piece of information that is also available online when looking for the maximum distance of an SR04 sensor.
> 
> Sorry I may be asking a stupid question, does "maxDistance" have to be the maximum distance the sensor can reach?

Well no, not necessarily but it sure shouldn't be **more** than the sensor can reach.

**Comment by LIYUHAN22** [comment]
> > > I am a bit concerned on your code reviewing process. sweat_smile The [docs](https://github.com/ItJustWorksTM/smce-gd/wiki/Vehicle-Capabilities#ultrasonic-distance-sensor) specify what is the maximum distance for the particular sensor, a piece of information that is also available online when looking for the maximum distance of an SR04 sensor.
> > 
> > 
> > Sorry I may be asking a stupid question, does "maxDistance" have to be the maximum distance the sensor can reach?
> 
> Well no, not necessarily but it sure shouldn't be **more** than the sensor can reach.

Thank you! we find our problem now

**Pull request merged**
